export default{
    "ward": "Ward",
    "booth": "Booth",
    "name": "Name",
    "contact": "Contact Number",
    "govtID": "Government Photo ID:",
    "function": "Function:",
    "age": "Age",
    "gender": "Gender",
    "religion": "Religion ",
    "caste": "Caste ",
    "subcaste": "Sub-Caste",
    "emailID": "Email Address",
    "Education": "Education",
    "profession": "Profession",
    "address": "Address",
    "totalWork": "How many hours can you spend for party work in a week?",
    "weekday": "Time of Availability in Weekdays",
    "weektime": "Timing of Availability during weekdays",
    "weekend": "Time of Availability in Weekend",
    "weektimeend": "Timing of Availability during weekend",
    "lastmonth": "Time of Availability in the last 1 month of Campaign",
    "timemonth": "Timing of Availability during last month",
    "totalvoter": "How many voters they are in direct contact with Contact Numbers.",
    "campaign": "Mode of Campaign :",
    "vehicleNo": "Vehicle Number :",
    "influencers": "Number of local influencers identified in the booth :",
    "verified_by": "Verified By",
    "remark": "Remark",
    "date":"Date",
    "verification_status":"Verification Status",
    "user_id":"User ID"
}