export default{
    "ward": "Ward",
    "booth": "Booth",
    "issues": "Key Issues and Challenges in booth :",
    "impArea": "Important Areas for planning Rally and meetings :",
    "events": "Time to plan important events and meetings with MLA:",
    "women": "Do you have strong women group ?",
    "womenNo": "Number of women members",
    "youth": "Do you have a youth team ?",
    "youthNo": "Number of youth members",
    "senior": "Do you have a senior citizen team ?",
    "seniorNo": "Number of senior members",
    "lessVote": "Which are the areas where vote bank is less and people are not happy ?",
    "noMeeting": "How many booth committee meetings happening every month ?",
    "voters": "Total number of voters",
    "votersturnOver": "Total turnover of voters",
    "toHouses": "Total number of houses",
    "casteVote": "Number of votes as per caste.",
    "associations": "List of important associations .",
    "religious": "List of important religious places .",
    "hotspot": "List of important hotsopts .",
    "WhatsApp": "Is WhatsApp group created ?",
    "chance": "Chances of winning as per Booth Committee Members",
    "voterSeg": "Type of Voter Segment",
    "date":"Date"
}